<template>
    <div>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Wanchalerm</td>
                </tr>
            </tbody>
        </table>
    </div>
</template>